version: 2
jobs:
  build:
    resource_class: xlarge
    docker:
      - image: mrkkrp/stackage-head:0.1.2
    environment:
      BUILD_PLAN: nightly-2018-04-26
      JOBS: 9
      FLAKY_PKGS: "--flaky threads --flaky lifted-async --flaky fsnotify-conduit --flaky hspec-core --flaky stm-delay"
    steps:
      - checkout
      - run:
          name: Get Nightly GHC build
          command: |
            mkdir -p $HOME/ghc-head-bindist
            curl -L https://ghc-artifacts.s3.amazonaws.com/nightly/validate-x86_64-linux/latest/bindist.tar.xz | tar -xJ --strip-components=1 -C $HOME/ghc-head-bindist
            curl https://ghc-artifacts.s3.amazonaws.com/nightly/validate-x86_64-linux/latest/metadata.json --output metadata.json
            cd $HOME/ghc-head-bindist
            ./configure --prefix=$HOME/ghc-head
            make install
      - run:
          name: Obtaining build plan
          command: |
            curl https://raw.githubusercontent.com/fpco/stackage-nightly/master/$BUILD_PLAN.yaml --output $BUILD_PLAN.yaml
      - restore_cache:
          keys:
            - new-build-reports-
      - restore_cache:
          keys:
            - new-stack-home
      - restore_cache:
          keys:
            - new-stack-work
      - run:
          name: Execute the build plan
          command: |
            stackage-curator make-bundle --allow-newer --jobs $JOBS --plan-file $BUILD_PLAN.yaml --docmap-file docmap-file.yaml --bundle-file bundle-file.yaml --target $BUILD_PLAN --skip-haddock --skip-hoogle --skip-benches --no-rebuild-cabal -v 2>&1 | tee build.log  || true
            stack setup
            stack build
            stack exec stackage-head -- add --build-url $CIRCLE_BUILD_URL --ghc-metadata metadata.json --build-log build.log --build-per-package-dir logs/nightly --target $BUILD_PLAN --outdir $HOME/build-reports
            stack exec stackage-head -- truncate --history-length 10 --outdir $HOME/build-reports
      - save_cache:
          key: new-stack-home
          paths: "/home/circleci/.stack"
      - save_cache:
          key: new-stack-work
          paths: ".stack-work"
      - save_cache:
          # This ensures that we push to the cache on every commit. If the
          # part with SHA1 is omitted, CircleCI may get too smart and skip
          # saving cache.
          key: new-build-reports-{{ .BuildNum }}
          paths:
            - /home/circleci/build-reports
      - run:
          name: Generate static site with the results
          command: |
            stack exec stackage-head -- generate-site --site-dir $HOME/site $FLAKY_PKGS --outdir $HOME/build-reports
      - run:
          name: Upload the site to S3 bucket
          command: |
            cd $HOME/site
            cp -v $HOME/project/.circleci/.s3cfg $HOME/.s3cfg
            s3cmd put --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY --region=$S3_REGION -P index.html s3://stackage-head/
            s3cmd sync --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY --region=$S3_REGION --delete-removed --skip-existing -P * s3://stackage-head/
      - run:
          name: Diff build results
          command: |
            stack exec stackage-head -- diff $FLAKY_PKGS --outdir $HOME/build-reports

workflows:
  version: 2
  triggered-build:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "0 0,6,12,18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
